"""
Pydantic Data Models for ATS Gap Analysis and Relevance Scoring.
Academic Alignment: Module V (Inference & Logic) & Module III (Heuristic Evaluation).
"""

from typing import List
from pydantic import BaseModel, Field


class SkillMatchItem(BaseModel):
    """Detailed status of a specific skill required by the JD."""
    skill_name: str = Field(..., description="Name of the skill or technology")
    is_present_in_resume: bool = Field(..., description="Whether candidate has verified evidence of this skill")
    importance: str = Field(default="Must-Have", description="Must-Have, Nice-to-Have, or Bonus")
    evidence_quote: str = Field(
        default="",
        description="Snippet or reference from candidate resume where skill was found"
    )


class MatchBreakdown(BaseModel):
    """Heuristic scoring breakdown across key dimensions."""
    hard_skills_score: int = Field(..., ge=0, le=100, description="Skill overlap score (50% weight)")
    project_relevance_score: int = Field(..., ge=0, le=100, description="Project relevance to JD (30% weight)")
    experience_education_score: int = Field(..., ge=0, le=100, description="Seniority and domain fit (20% weight)")


class MatchReport(BaseModel):
    """
    Comprehensive Match and Gap Analysis between Candidate and Job Description.
    Generated by Agent 4 (Match & Gap Analyzer).
    """
    job_id: str = Field(..., description="ID of the analyzed job listing")
    job_title: str = Field(..., description="Title of the job")
    company: str = Field(..., description="Company name")
    overall_match_score: int = Field(..., ge=0, le=100, description="Total ATS match score (0-100)")
    score_breakdown: MatchBreakdown = Field(..., description="Detailed component scores")
    matched_skills: List[str] = Field(default_factory=list, description="Skills candidate possesses that match JD")
    missing_skills: List[str] = Field(default_factory=list, description="Critical skills in JD missing from resume")
    strengths_summary: str = Field(..., description="Key competitive advantages of the candidate for this role")
    tailoring_recommendations: List[str] = Field(
        default_factory=list,
        description="Honest, high-impact edits to highlight in the tailored resume"
    )
