"""
Pydantic Data Models for Job Postings, Search Queries, and Recommended Roles.
Academic Alignment: Modules II & III (Uninformed & Informed Search, State Space Formulation).
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class JobListing(BaseModel):
    """Normalized structured representation of a job opening."""
    id: str = Field(..., description="Unique identifier for the job listing")
    title: str = Field(..., description="Standardized job title, e.g., 'Junior AI Engineer'")
    company: str = Field(..., description="Hiring company name")
    location: str = Field(default="Remote", description="Job location or Remote/Hybrid")
    employment_type: str = Field(default="Full-time", description="Full-time, Internship, Contract")
    experience_level: str = Field(default="Entry-level", description="Internship, Entry-level, Junior, Mid")
    description: str = Field(..., description="Full or summarized job description text")
    apply_link: str = Field(..., description="Direct link or portal link to apply")
    portal_name: str = Field(default="Web", description="Source portal (e.g., LinkedIn, Indeed, Dice, Google Jobs)")
    posted_date: Optional[str] = Field(None, description="When the position was published")
    required_skills: List[str] = Field(
        default_factory=list,
        description="Mandatory skills and tools extracted from the JD"
    )
    nice_to_have_skills: List[str] = Field(
        default_factory=list,
        description="Preferred or bonus skills mentioned in the JD"
    )
    salary_range: Optional[str] = Field(None, description="Comp range if available")


class JobSearchQuery(BaseModel):
    """Query state used by the search agent for query expansion and iteration."""
    role_title: str = Field(..., description="Target job title to search")
    location: str = Field(default="Remote", description="Target location")
    experience_level: str = Field(default="Entry-level", description="Target seniority")
    expanded_keywords: List[str] = Field(
        default_factory=list,
        description="Alternative titles and domain keywords generated by the agent"
    )
    max_results: int = Field(default=5, description="Number of results to retrieve")


class RoleRecommendation(BaseModel):
    """Specific career role suggested for the candidate."""
    role_title: str = Field(..., description="Title of the recommended role")
    fit_score: int = Field(..., ge=0, le=100, description="Estimated fit percentage (0-100)")
    rationale: str = Field(..., description="Detailed explanation of why the candidate's profile matches this role")
    key_matching_strengths: List[str] = Field(
        default_factory=list,
        description="Candidate's top skills or projects that align with this role"
    )
    recommended_search_keywords: List[str] = Field(
        default_factory=list,
        description="Optimized keywords for querying job search portals"
    )


class RoleRecommendationResponse(BaseModel):
    """Output contract for Agent 2 (Role Recommender)."""
    candidate_summary_analysis: str = Field(
        ...,
        description="High-level evaluation of the candidate's core domain and readiness"
    )
    recommended_roles: List[RoleRecommendation] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="Top 3 to 5 tailored job positions"
    )
